version: '2'
 
services:
  mysql:
    image: mysql
    container_name: test-mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
    volumes:
      - /home/preetham/docker/data/mysql-datadir:/var/lib/mysql
